/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modals/add`; params?: Router.UnknownInputParams; } | { pathname: `/modals/reschedule-modal`; params?: Router.UnknownInputParams; } | { pathname: `/modals/take-medication-modal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/screen-1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/screen-2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/screen-3`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/schedule`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modals/add`; params?: Router.UnknownOutputParams; } | { pathname: `/modals/reschedule-modal`; params?: Router.UnknownOutputParams; } | { pathname: `/modals/take-medication-modal`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/screen-1`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/screen-2`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/screen-3`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/schedule`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modals/add${`?${string}` | `#${string}` | ''}` | `/modals/reschedule-modal${`?${string}` | `#${string}` | ''}` | `/modals/take-medication-modal${`?${string}` | `#${string}` | ''}` | `/onboarding/screen-1${`?${string}` | `#${string}` | ''}` | `/onboarding/screen-2${`?${string}` | `#${string}` | ''}` | `/onboarding/screen-3${`?${string}` | `#${string}` | ''}` | `/tabs/notifications${`?${string}` | `#${string}` | ''}` | `/tabs/schedule${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modals/add`; params?: Router.UnknownInputParams; } | { pathname: `/modals/reschedule-modal`; params?: Router.UnknownInputParams; } | { pathname: `/modals/take-medication-modal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/screen-1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/screen-2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/screen-3`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/schedule`; params?: Router.UnknownInputParams; };
    }
  }
}
